name: CD

on:
  workflow_run:
    workflows: [ "ci" ]
    types:
      - completed

jobs:

  bundle:
    name: Build Release AAB
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Check gradlew permissions
        run: ls -l ${{ github.workspace }}/gradlew

      - name: Build Release AAB
        run: ./gradlew bundleRelease

      - name: Sign App Bundle
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Upload Signed AAB
        uses: actions/upload-artifact@v2
        with:
          name: app-bundle
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

      - name: Sign app bundle
        uses: r0adkll/upload-google-play@v1
        id: sign_app
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.bulletapps.candypricer
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
        env:
          BUILD_TOOLS_VERSION: "30.0.2"

      - name: Upload Signed AAB
        uses: actions/upload-artifact@v2
        with:
          name: app-bundle
          path: app/build/outputs/bundle/release/app-release.aab

  deploy:
    name: Deploy release AAB on Playstore
    needs: [ bundle ]
    runs-on: ubuntu-latest
    steps:
      - name: Create service_account.json
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Deploy to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: ${{ github.event.inputs.app_id }}
          releaseFiles: app/build/outputs/bundle/release/*.aab
          track: production